name: Deploy Static Site to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to S3
      run: |
        aws s3 sync ./website s3://$S3_BUCKET_NAME --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        AWS_REGION: "us-east-1"

    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"
      env:
        CLOUDFRONT_ID: ${{ secrets.CLOUDFRONT_ID }}
